[tool.poetry]
name="oc-query"
version="1.0"
description=""
authors=["Amazon Web Services"]

[tool.poetry.dependencies]
python="^3.13"
langchain="^0.3.27"
langchain-core="^0.3.80"
langchain-aws="^0.2.32"
langchain-community="^0.3.29"
